# Generated by nixos-generate-config. Keep machine-specific filesystems and
# hardware settings here; put intentional policy changes in the host or modules.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-e1ee714e-7d09-401f-a3a6-5857370e2549";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e1ee714e-7d09-401f-a3a6-5857370e2549".device =
    "/dev/disk/by-uuid/e1ee714e-7d09-401f-a3a6-5857370e2549";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/166A-3B43";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-98f0177e-68cc-4775-bdf2-fd6a2b55fe30"; }
  ];

  boot.initrd.luks.devices."luks-98f0177e-68cc-4775-bdf2-fd6a2b55fe30".device =
    "/dev/disk/by-uuid/98f0177e-68cc-4775-bdf2-fd6a2b55fe30";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
